import '../styles/globals.css'
import { GlobalProvider } from './context'

//

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <GlobalProvider>
        {children}
      </GlobalProvider>
      </body>
    </html>
  )
}
